---
# yamllint disable rule:line-length rule:truthy
os: linux
dist: focal
language: ruby
cache: bundler
before_install:
  - yes | gem update --system
  - bundle --version
script:
  - 'bundle exec rake $CHECK'
jobs:
  fast_finish: true
  include:
    - rvm: 2.4.4
      bundler_args: --without system_tests development release
      env: PUPPET_VERSION="~> 5.0" CHECK=test
    - rvm: 2.5.3
      bundler_args: --without system_tests development release
      env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
    - rvm: 2.5.3
      bundler_args: --without system_tests development release
      env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
    - rvm: 2.4.4
      bundler_args: --without system_tests development release
      env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=ubuntu1604-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=ubuntu1604-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=ubuntu1804-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=ubuntu1804-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=centos6-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=centos6-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=centos7-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=centos7-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=debian8-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=debian8-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=debian9-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=debian9-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_setfile=debian10-64 CHECK=beaker
      services: docker
    - rvm: 2.5.3
      bundler_args: --without development release
      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_setfile=debian10-64 CHECK=beaker
      services: docker
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
  webhooks: https://voxpupu.li/incoming/travis
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  username: puppet
  password:
    secure: "k2eyprVmf+1ouw86/4rhyQ/j/cf/uJly5Gww282NibxexQLqEgWwqm0ivgADv6T952J6n6AHAHhtAAq+PZ6NEUfGjM0vl99EH44Le92dp4b2EwW35kbbs7pfmnLMnyt5A6mLevUAcTmMZHKXAcS/8VWHx9elahm1o9d2VU0Vl+sEbdisPPK76nqa1G9BaTlSud7AEl3PT09HMyMDeYJBRU8S1I3vVckEulK+MMEeMwTNFaUtdnHSSo1Ky6DaoRTOFaioz187QTzcIvYnARjYiNwo/ucvekFcCAZXmym4Xhz3UlUTm+Gjf4tXHUD2UoI09Vs6Cz+0lhN90tNJvIiz4D1qNMfFSoQzGm+1eG/sAsmWzdBSggC/EBPPPqT4TTLV0fsmUZwUGgpqQGU0XripMLEPmhdeAbH9o1oprUGuNSPXtrjO1nA0U1gWbrC2w9ko2y00YOFxGEL11uKvQyeWTL2WFIy/FvqxJvg1lkA+AU8+DfWKhKcE7lmFqsqAYyknHQ1H33AeSIlD4xg3foCRQh6XpTdxnHrus5iT9xuAkv45TvwiU+jH+K0mTNi6E1XzFL9GizyQprkpE14wQAwTEgdvi3LRaeNxlkzLUgrbQhWEyIiwGtB9tbCoZiLrMQw2LdNTrz0iS23KPh85gF2YlsxDYYA5TmSdzSiwkEEDl9U="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
